# Metadata Schema Configuration

# Define metadata fields that can be extracted
metadata_fields:
  department:
    type: "STRING"
    options: ["sales", "engineering", "hr", "finance", "marketing", "operations"]
    description: "Department that owns or created the document"
  
  document_type:
    type: "STRING"
    options: ["minutes", "report", "proposal", "contract", "manual", "memo", "others"]
    description: "Category of document"
  
  sensitivity_level:
    type: "STRING"
    options: ["public", "internal", "confidential", "restricted"]
    description: "Data sensitivity classification"
  
  tags:
    type: "STRING_LIST"
    description: "Relevant keywords and topics (3-5 tags)"
  
  author:
    type: "STRING"
    description: "Document author or creator"
  
  creation_date:
    type: "STRING"
    description: "Document creation date (YYYY-MM-DD format)"
  
  data_period:
    type: "STRING"
    description: "Time period covered by data (e.g., 2024Q1, January 2024)"
  
  record_count:
    type: "NUMBER"
    description: "Number of records in tabular data"
  
  is_active:
    type: "BOOLEAN"
    description: "Whether document is currently active/valid"

# Path-based deterministic rules (highest priority)
path_rules:
  - pattern: "{department}/{document_type}/**"
    extractions:
      department: "{department}"
      document_type: "{document_type}"

# File type rules for content-based extraction
file_type_rules:
  table_data:
    - extensions: [".csv", ".xlsx"]
      use_columns_for_metadata: true
  text_files:
    - extensions: [".txt", ".md", ".pdf"]
      use_columns_for_metadata: false
  
# Bedrock Configuration
bedrock:
  model_id: "global.anthropic.claude-haiku-4-5-20251001-v1:0"
  max_tokens: 64000
  input_context_window: 200000
  temperature: 0.1
