# Metadata Generation Rules Configuration

rules:
  file_patterns:
    # PDF documents
    - pattern: "**/*.pdf"
      schema:
        type: "object"
        properties:
          department:
            type: "string"
            description: "Department name (e.g., Sales, Engineering, HR)"
          document_type:
            type: "string"
            enum: ["contract", "report", "proposal", "manual", "others"]
            description: "Type of document"
          sensitivity_level:
            type: "string"
            enum: ["public", "internal", "confidential", "restricted"]
            description: "Sensitivity level"
          author:
            type: "string"
            description: "Author name"
          creation_date:
            type: "string"
            format: "date"
            description: "Creation date (YYYY-MM-DD format)"
          summary:
            type: "string"
            description: "Document summary (max 100 words)"
        required: ["department", "document_type", "sensitivity_level"]

    # CSV/Excel files in reports directory
    - pattern: "reports/**/*.csv"
      schema:
        type: "object"
        properties:
          department:
            type: "string"
            description: "Department name"
          document_type:
            type: "string"
            const: "tabular_data"
          sensitivity_level:
            type: "string"
            enum: ["public", "internal", "confidential", "restricted"]
            description: "Sensitivity level"
          data_period:
            type: "string"
            description: "Data period (e.g., January 2024, 2024Q1)"
          columns_summary:
            type: "string"
            description: "Summary of main columns"
          record_count:
            type: "integer"
            description: "Approximate number of records"
        required:
          ["department", "document_type", "sensitivity_level", "data_period"]

    - pattern: "reports/**/*.xlsx"
      schema:
        type: "object"
        properties:
          department:
            type: "string"
            description: "Department name"
          document_type:
            type: "string"
            const: "tabular_data"
          sensitivity_level:
            type: "string"
            enum: ["public", "internal", "confidential", "restricted"]
            description: "Sensitivity level"
          data_period:
            type: "string"
            description: "Data period (e.g., January 2024, 2024Q1)"
          columns_summary:
            type: "string"
            description: "Summary of main columns"
        required:
          ["department", "document_type", "sensitivity_level", "data_period"]

    # Text files
    - pattern: "**/*.txt"
      schema:
        type: "object"
        properties:
          department:
            type: "string"
            description: "Department name"
          document_type:
            type: "string"
            enum: ["memo", "minutes", "manual", "others"]
            description: "Type of document"
          sensitivity_level:
            type: "string"
            enum: ["public", "internal", "confidential", "restricted"]
            description: "Sensitivity level"
          keywords:
            type: "string"
            description: "Main keywords of the document (3-5 words, comma-separated)"
        required:
          ["department", "document_type", "sensitivity_level", "keywords"]

    # Markdown files
    - pattern: "**/*.md"
      schema:
        type: "object"
        properties:
          department:
            type: "string"
            description: "Department name"
          document_type:
            type: "string"
            enum: ["document", "manual", "README", "others"]
            description: "Type of document"
          sensitivity_level:
            type: "string"
            enum: ["public", "internal", "confidential", "restricted"]
            description: "Sensitivity level"
          keywords:
            type: "string"
            description: "Main keywords of the document (3-5 words, comma-separated)"
          summary:
            type: "string"
            description: "Document summary (max 100 words)"
        required:
          ["department", "document_type", "sensitivity_level", "keywords"]

# Bedrock Configuration
bedrock:
  model_id: "global.anthropic.claude-haiku-4-5-20251001-v1:0"
  max_tokens: 2000
  temperature: 0.1
