[project]
name = "metadata-generator"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.34.0",
    "pyyaml>=6.0",
    "jsonschema>=4.20.0",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.0.0",
]
